[build]
  command = "npm run build" # Atur perintah yang sesuai dengan cara Anda membangun aplikasi Next.js
  publish = "out" # Sesuaikan dengan folder output dari build Anda

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200