import Header from "../components/layout/Header";
import "./globals.css";
import { Poppins } from "next/font/google";
// import MainFooter from "@/components/Footer";
import DefaultNavbar from "../components/Header";
import Footer from "@/components/layout/Footer";

const inter = Poppins({ weight: "400", preload: false });
// const inter = Poppins({ subsets: ['latin'] })

export const metadata = {
  title: "Home | Dede Firmansah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="flex flex-col min-h-screen">
          <div className="flex-grow">
            <div className="container w-full max-w-4xl mx-auto">{children}</div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
