import Header from "../components/layout/Header";
import "./globals.css";
import { Poppins } from "next/font/google";
// import MainFooter from "@/components/Footer";
import DefaultNavbar from "../components/Header";

const inter = Poppins({ weight: "400", preload: false });
// const inter = Poppins({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        <Header />
        {children}
        {/* <MainFooter /> */}
      </body>
    </html>
  );
}
